version: '2'
services:

    django-slave-2:
      build: docker-postgis
      container_name: agritechnovation-gis-db-slave-2
      restart: always
      environment:
        ALLOW_IP_RANGE: '0.0.0.0/0'
        REPLICATE_FROM: '169.255.170.137'
        REPLICATE_PORT: '6001'
        USERNAME: 'docker'
        PASS: 'Agritechnovation!#%'

      # You can expose the port to observe it in your local machine
      # For this sample, it was disabled by default to allow scaling test
      ports:
        - "6000:5432"

    gis-slave:
      build: docker-postgis
      container_name: agritechnovation-gis-db-slave
      restart: always
      environment:
        ALLOW_IP_RANGE: '0.0.0.0/0'
        REPLICATE_FROM: '169.255.170.137'
        REPLICATE_PORT: '6001'
        USERNAME: 'docker'
        PASS: 'Agritechnovation!#%'

      # You can expose the port to observe it in your local machine
      # For this sample, it was disabled by default to allow scaling test
      ports:
        - "6001:5432"